"""Publish HTML BDD test report to JIRA Test Execution issue.

**Purpose**: The script is designed to be used in a CI/CD pipeline to publish
the HTML BDD test report to the JIRA Test Execution issue that corresponds to
the current CI job. This script essentially creates a link to the HTML BDD test
report (generated by the ``pytest-bdd-report`` plugin) and appends it to the
description of the JIRA Test Execution issue that corresponds to the current CI
job.

**Expected inputs**: The script expects the following.

- Some environment variables:
  - ``CI_JOB_URL``: the URL of the current CI job, if availabl
  - ``JIRA_URL``: the URL of the JIRA instance,
  - ``JIRA_AUTH``: the authentication token for the JIRA API,
  - ``HTML_REPORT_TARGET_FILE``: the relative path of the HTML BDD test report,
    artifact in the CI job.
  - ``TEST_DOCS_LINK`: link to the test documentation. If provided, it will be
    used to update the JIRA issue description. If not provided, that part of
    the description will be omitted.

- An already existing JIRA ticket in the project with key
  ``PROJECT_KEY="XTP"``,
  which is expected to be unique and to contain somewhere the ``CI_JOB_URL``
  in the description.
- An already existing HTML BDD test report, which can be generated
  through the ``pytest-bdd-report`` plugin, adding the
  ``--bdd-report FILENAME`` option to the pytest command.

  The report is expected to be an artifact of the CI job,
  available at the relative position pointed by the
  ``HTML_REPORT_TARGET_FILE`` env variable
  (or otherwise in the default location ``build/report.html``).

**Constants**:

- a fixed ``PROJECT_KEY="XTP"`` is used to identify the project in JIRA,
- a default ``REPORT_DESCRIPTION_TEMPLATE`` is used to create the
  text to append to the JIRA issue description.

**Program flow**. The script performs the following steps:

1. verifies the presence of the required environment variables,
2. verifies the presence of the file containing the HTML BDD test report
   (currently deactivated),
3. searches for the JIRA issue that corresponds to the current CI job,
4. updates the JIRA issue description with a link to the HTML BDD test report.

During the execution, some logs are printed to the console (e.g., with a
reference to the JIRA ticket found and the link to the HTML report).

The script raises an exception if any of the required steps fails.

**Dependencies**: none, except the Python standard library and the
``requests`` library.
"""

import logging
import os

import requests

# -----------------------------------------------------------
# Needed environment variables and settings

CI_JOB_URL = os.getenv("CI_JOB_URL")
"""The expected URL of the current CI job.

Example: https://gitlab.com/ska-telescope/ska-tmc/ska-tmc-mid-integration/-/jobs/7620579897

NOTE: Do not put a final slash in the path
(e.g., avoid
https://gitlab.com/ska-telescope/ska-tmc/ska-tmc-mid-integration/-/jobs/7620579897/
and use instead
https://gitlab.com/ska-telescope/ska-tmc/ska-tmc-mid-integration/-/jobs/7620579897).
"""  # pylint: disable=line-too-long # noqa: E501

JIRA_URL = os.getenv("JIRA_URL")
"""The URL of the JIRA instance.

Example: https://jira.skatelescope.org

NOTE: Do not put a final slash in the path
(e.g., avoid https://jira.skatelescope.org/ and use instead
https://jira.skatelescope.org).
"""

JIRA_AUTH = os.getenv("JIRA_AUTH")
"""The authentication token for the JIRA API (secret)."""

HTML_REPORT_TARGET_FILE = os.getenv(
    "HTML_REPORT_TARGET_FILE", "build/report.html"
)
"""The relative path of the HTML BDD test report artifact in the CI job.

Default: build/report.html

NOTE: Do not put a leading slash in the path
(e.g., "build/report.html" instead of "/build/report.html").
"""

TEST_DOCS_LINK = os.getenv("TEST_DOCS_LINK", None)

PROJECT_KEY = "XTP"
"""The key of the project in JIRA (for now, it is a fixed value)."""


def env_vars_to_str() -> str:
    """Get a string representation of the environment variables.

    :return: a string representation of the environment variables, hiding the
        JIRA_AUTH value if it is set.
    """
    msg = f"CI_JOB_URL: {CI_JOB_URL}, JIRA_URL: {JIRA_URL}, "
    msg += f'JIRA_AUTH: {"[something]" if JIRA_AUTH else "[None]"}, '
    msg += f"PROJECT_KEY: {PROJECT_KEY}, "
    msg += f"HTML_REPORT_TARGET_FILE: {HTML_REPORT_TARGET_FILE}"
    return msg


def check_env_vars() -> None:
    """Check if the required environment variables are set.

    The function raises an exception if any of the required environment
    variables is not set. Otherwise, it does nothing.

    :raises ValueError: if any of the required environment variables
        is not set.
    """
    if not CI_JOB_URL or not JIRA_URL or not JIRA_AUTH or not PROJECT_KEY:
        raise ValueError(
            "Missing one or more environment variables: " + env_vars_to_str()
        )


# -----------------------------------------------------------
# Report file location and description


def get_report_link() -> str:
    """Get a web link to the HTML BDD test report.

    The link is built starting from the CI job URL and the relative path of the
    HTML BDD test report.

    NOTE: A transformation is needed to reach the report from
    the CI job URL, since while the CI job URL is like:

    https://gitlab.com/ska-telescope/ska-tmc/ska-tmc-mid-integration/-/jobs/7620579897

    the report URL (base) instead is like:

    https://ska-telescope.gitlab.io/-/ska-tmc/ska-tmc-mid-integration/-/jobs/7620579897

    :return: the URL of the HTML BDD test report. NOTE: the link may be not
        anymore valid after the CI job expiration.
    """  # pylint: disable=line-too-long # noqa: E501
    artifact_job_base_url = CI_JOB_URL.replace(
        "gitlab.com/ska-telescope", "ska-telescope.gitlab.io/-"
    )
    return artifact_job_base_url + "/artifacts/" + HTML_REPORT_TARGET_FILE


REPORT_DESCRIPTION_TEMPLATE = (
    "\n\nHTML BDD execution report: {report_link}\n\n"
    "*NOTE*: The link may be not anymore valid after the CI job expiration. "
    "If you think this report is expired, check the latest CI job ticket "
    "for your branch.\n\n"
)
"""The template to the text to append to the JIRA issue description
to describe the HTML BDD test report.

It has a placeholder for the report link.
"""


def get_report_description() -> str:
    """Return a description to append to the JIRA issue.

    :return: the description to append to the JIRA issue.
    """
    msg = REPORT_DESCRIPTION_TEMPLATE.format(report_link=get_report_link())

    if TEST_DOCS_LINK:
        msg += f"Test documentation: {TEST_DOCS_LINK}\n\n"
    return msg

def check_report_file_accessible() -> None:
    """Check if the HTML BDD test is accessible from the CI job artifacts.

    The function raises an exception if the file is not accessible through
    a GET request to the computed URL. Otherwise, it does nothing.

    NOTE: deactivated! Currently has status code 403.

    :raises FileNotFoundError: if the file is not accessible.
    """
    report_url = get_report_link()
    response = requests.get(report_url)
    if response.status_code != 200:
        msg = f"Failed to access the HTML BDD test report at {report_url}. "
        msg += f"Status code: {response.status_code}. "
        msg += f"Response:\n{response.text}. "
        msg += "Please, check you set correctly the HTML_REPORT_TARGET_FILE "
        msg += "and check that an HTML BDD test report is actually generated."
        raise FileNotFoundError(msg)


# -----------------------------------------------------------
# Communication with JIRA


def auth_header() -> dict:
    """Get the authorization header needed to interact with JIRA API.

    :return: the authorization header, containing the
        Basic Authentication token.
    """
    return {"Authorization": f"Basic {JIRA_AUTH}"}


def search_jira_execution_issue(target_ci_job_url: str) -> list[dict]:
    """Search in JIRA issue that corresponds to a certain CI job URL.

    :param target_ci_job_url: the URL of the CI job to search in the
        JIRA issues.

    :return: a list of JIRA issues that contain the CI job URL in the
        description.

    :raises RuntimeError: if the search request fails.
    """
    query = (
        f'project = "{PROJECT_KEY}" '
        'AND issuetype = "Test Execution" '
        f'AND description ~ "{target_ci_job_url}"'
    )

    search_api_path = "/rest/api/2/search"
    search_api_url = f"{JIRA_URL}{search_api_path}"

    logging.info(
        "Searching a JIRA ticket containing the CI job URL: %s",
        target_ci_job_url,
    )

    # Perform the search
    response = requests.get(
        search_api_url, headers=auth_header(), params={"jql": query}
    )

    # Check the response status
    if response.status_code != 200:
        msg = "Failed to search a JIRA ticket containing the CI job URL "
        msg += f"{target_ci_job_url}. "
        msg += f"Status code: {response.status_code}. "
        msg += f"Response:\n{response.text}"
        raise RuntimeError(msg)

    return response.json().get("issues", [])


def append_text_to_issue_description(issue: dict, new_text: str) -> None:
    """Append a text to the description of a JIRA issue.

    :param issue: the JIRA issue to update, as the dictionary object
        returned by the JIRA API.
    :param new_text: the text to append to the description of the JIRA issue.

    :raises RuntimeError: if the update request fails.
    """
    issue_ticket = issue["key"]

    update_api_path = f"/rest/api/2/issue/{issue_ticket}"
    update_api_url = f"{JIRA_URL}{update_api_path}"

    # the update appends to the description the given new text
    update_payload = {
        "fields": {
            "description": issue["fields"]["description"] + new_text,
        }
    }

    logging.info(
        "Updating JIRA ticket %s description with links to generated reports",
        issue_ticket,
    )

    response = requests.put(
        update_api_url, headers=auth_header(), json=update_payload
    )

    if response.status_code == 204:
        logging.info("Updated successfully the JIRA ticket %s", issue_ticket)
    else:
        msg = f"Failed to update JIRA ticket {issue_ticket}:\n"
        msg += f"status code: {response.status_code}\n"
        msg += f"URL: {update_api_url}\n"
        msg += f"Payload: {update_payload}\n"
        msg += f"Response: {response.text}\n"
        raise RuntimeError(msg)


def get_issue_link(issue) -> str:
    """Get the link to the JIRA issue.

    :param issue: the JIRA issue object.

    :return: the link to the JIRA issue.
    """
    return JIRA_URL + "/browse/" + issue["key"]


def print_issues_links(issues):
    """Print the links to the JIRA issues."""
    issues_msg = "\nThis job is related to the following JIRA issues:"
    for issue in issues:
        issues_msg += f"\n- {get_issue_link(issue)}"
    issues_msg += "\n"
    logging.info(issues_msg)


# -----------------------------------------------------------
# Program entry point


if __name__ == "__main__":
    logging.basicConfig(level=logging.DEBUG)

    initial_msg = (
        "Publishing the HTML BDD test report link "
        f"({get_report_link()}) "
        f"to the JIRA Test Execution issue "
        f"that corresponds to the CI job at {CI_JOB_URL}."
    )
    logging.info(initial_msg)

    # 1. Check the environment variables
    check_env_vars()

    # 2. Check the HTML BDD test report file
    # NOTE: currently deactivated because the report may not be accessible
    # to a non-logged user.
    # check_report_file_accessible()

    # 3. Search for the JIRA issue that corresponds to the current CI job
    issues = search_jira_execution_issue(CI_JOB_URL)

    if not issues:
        raise RuntimeError(
            "No JIRA Test Execution issue found for the CI job "
            f"at {CI_JOB_URL}. "
            "We cannot publish the further test reports to JIRA."
        )

    print_issues_links(issues)

    if len(issues) > 1:
        logging.warning(
            "Found multiple JIRA Test Execution issues for the CI job %s "
            "We will update just the first one.",
            CI_JOB_URL,
        )

    # 4. Update the JIRA issue description with the link
    # to the HTML BDD test report
    append_text_to_issue_description(issues[0], get_report_description())

    completition_msg = (
        f"The {get_report_link()} HTML BDD test report has been "
        "successfully published to JIRA "
        f"in the issue {get_issue_link(issues[0])}."
    )
    logging.info(completition_msg)
