k8s-test-tmc-with-sdp:
  extends:
    - k8s-test
  variables:
    TELESCOPE: 'SKA-mid'
    PORT: "10000"
    KUBE_NAMESPACE: 'ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-tmc-sdp'
    KUBE_NAMESPACE_SDP: 'ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-sdp'
    SERVICE_ACCOUNT: "ci-svc-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-tmc-sdp"
    MARK: 'tmc_sdp'
    SDP_SIMULATION_ENABLED: 'false'
  before_script:
    - make cred SERVICE_ACCOUNT=$SERVICE_ACCOUNT
    - '[ -f .make/k8s.mk ] || (echo "File k8s.mk not included in Makefile; exit 1")'
    - 'make help | grep k8s-test'
    - make k8s-install-chart
    - chmod u=rwx,go=rx tests/scripts/sdp_data_copy.sh
    - ${PWD}/tests/scripts/sdp_data_copy.sh create_pod
    - make k8s-wait
    - make k8s-wait KUBE_APP="ska-sdp"
  environment:
    name: test/$CI_COMMIT_REF_SLUG-sdp
    on_stop: stop-k8s-test-tmc-with-sdp
    auto_stop_in: 1 minute


stop-k8s-test-tmc-with-sdp:
  extends:
    - stop-k8s-test
  variables:
    KUBE_NAMESPACE: 'ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-tmc-sdp'
    KUBE_NAMESPACE_SDP: 'ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-sdp'
    SDP_SIMULATION_ENABLED: 'false'
  script:
    - ${PWD}/tests/scripts/sdp_data_copy.sh delete_pod
    - make k8s-uninstall-chart
    - kubectl -n $KUBE_NAMESPACE delete pods,svc,daemonsets,deployments,replicasets,statefulsets,cronjobs,jobs,ingresses,configmaps --all
    - make k8s-delete-namespace
  environment:
    name: test/$CI_COMMIT_REF_SLUG-sdp
    action: stop
