global:
  minikube: false
  operator: true
  exposeALLDS: false

labels: 
  app: ska-tmc-integration

# DISH LMC
ska-mid-dish-manager:
  enabled: true
  dishmanager:
    image:
      registry: artefact.skao.int
      image: ska-mid-dish-simulators
      tag: 5.0.1
      pullPolicy: IfNotPresent
  labels:
    app: ska-tmc-integration


ska-mid-dish-simulators:
  dishsimulators:
    image:
      registry: artefact.skao.int
      image: ska-mid-dish-simulators
      tag: 4.1.2
      pullPolicy: IfNotPresent
  labels:
    app: ska-tmc-integration
  enabled: true
  deviceServers:
    spfdevice:
      enabled: true
    spfrxdevice:
      enabled: true
  dsOpcuaSimulator:
    enabled: true

ska-mid-dish-ds-manager:
  labels:
    app: ska-tmc-integration
  enabled: true
  dishstructuremanager:
  image:
    registry: artefact.skao.int
    image: ska-mid-dish-ds-manager
    tag: 2.1.2
    pullPolicy: IfNotPresent

