display: ":0"
xauthority: "~/.Xauthority"

global:
  labels:
    app: ska-mid-integration
  minikube: false
  operator: true
  exposeAllDS: true
  taranta_auth_enabled: false
  taranta_dashboard_enabled: false

  sub-system:
    tango-base:
      enabled: false
    ska-tango-base:
      enabled: false
    ska-taranta:
      enabled: false

  retry:
    - "--sleep=3"
    - "--tries=100"

  tango_host: databaseds:10000
  device_server_port: 45450
  cluster_domain: cluster.local
  clusterDomain: cluster.local

  dishes: ["001", "036", "063", "100"]
  namespace_dish:
    dish_names:
      - mid-dish/dish-manager/SKA001
      - mid-dish/dish-manager/SKA036
      - mid-dish/dish-manager/SKA063
      - mid-dish/dish-manager/SKA100

  data-product-pvc-name: shared
  dsconfig:
    timeout: 300s
    image:
      registry: artefact.skao.int
      image: ska-tango-images-tango-dsconfig
      tag: 1.5.1
      pullPolicy: IfNotPresent
  itango:
    image:
      registry: artefact.skao.int
      image: ska-tango-images-tango-itango
      tag: 9.3.10
      pullPolicy: IfNotPresent
  tango_example:
    image:
      registry: harbor.skao.int/production
      image: ska-tango-examples
      tag: 0.4.32
      pullPolicy: IfNotPresent

  # Required by ska-sdp.
  kafka_host: ska-mid-integration-kafka
  sdp:
    processingNamespace: ska-mid-integration-sdp

ska-tango-base:
  enabled: true
  vnc:
    replicas: 1
    enabled: true
  tangorest:
    replicas: 1
    enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
        ephemeral-storage: 256Mi
      limits:
        cpu: 200m
        memory: 768Mi
        ephemeral-storage: 256Mi
  tangotest:
    enabled: true
  ingress:
    enabled: true
    hostname: k8s.stfc.skao.int
  tangodb:
    use_pv: false

#=== SDP ===#
ska-sdp:
  enabled: true
  labels:
    app: ska-mid-integration
  ska-tango-base:
    enabled: false
  lmc:
    prefix: mid
    nsubarray: 3
    strictValidation: true
  data-pvc:
    pod:
      enabled: true
    create:
      enabled: true
      size: 20Gi
      storageClassName: nfss1
  qa:
    display:
      vault:
        useVault: false
  scripts:
    url: tmdata::car:sdp/ska-sdp-script?3.0.0

# Required by recent SDP versions.
ska-tango-alarmhandler:
  enabled: true

# Kafka configuration used by SDP.
kafka:
  enabled: true
  image: apache/kafka
  version: 3.8.0
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 1000m
      memory: 1024Mi
    limits:
      cpu: 2000m
      memory: 4096Mi

#=== CSP ===#
ska-csp-lmc-mid:
  labels:
    app: ska-mid-integration
  enabled: true
  enablePss: false

ska-mid-cbf-tdc-mcs:
  enabled: true
  legacy_compatibility: true
  labels:
    app: ska-mid-integration
  num_subarrays: 1

ska-pst-lmc:
  enabled: false

ska-mid-cbf-tdc-tmleafnode:
  enabled: true
  labels:
    app: ska-mid-integration

#=== DISH ===#
ska-dish-lmc:
  enabled: true
  ska-tango-base:
    enabled: false
  ska-mid-dish-manager:
    enabled: true
    dishmanager:
      actions:
        timeout_seconds: "300"
  ska-mid-dish-ds-manager:
    enabled: true
  ska-mid-dish-simulators:
    enabled: true
    deviceServers:
      spfdevice:
        enabled: true
      spfrxdevice:
        enabled: true
    dsOpcuaSimulator:
      enabled: true

#=== TMC MID ===#
ska-tmc-mid:
  enabled: true
  legacy_compatibility: true
  telescope: SKA-mid
  ska-tango-base:
    enabled: false
  deviceServers:
    centralnode:
      CommandTimeOutDefault: 150
      global_pointing_model:
        version: "1.13.2"
        interface: "https://schema.skao.int/ska-mid-dish-gpm/1.2"
        data_sources_prefix: "gitlab://gitlab.com/ska-telescope/ska-tmc/ska-tmc-simulators"
        file_path_prefix: "instrument/ska_mid1/global_pointing_model_data"
      DishVccConfig:
        DishVccUri: "car://gitlab.com/ska-telescope/ska-tmc/ska-tmc-simulators?1.13.2#tmdata"
        DishVccFilePath: "instrument/dishid_vcc_map_configuration/ska-mid-cbf-system-parameters.json"
        Enabled: "true"
        DishKvalueAggregationAllowedPercent: "100.0"
      DishVccInitTimeout: 180
    subarraynode:
      CommandTimeOutDefault: 150
      AbortCommandTimeOut: 180
    sdpsubarrayleafnode:
      CommandTimeOutDefault: 50
      AdapterTimeOut: 2
    sdpmasterleafnode:
      AdapterTimeOut: 2
    cspmasterleafnode:
      CommandTimeOutDefault: 30
      AdapterTimeOut: 2.0
    cspsubarrayleafnode:
      CommandTimeOutDefault: 50
      AdapterTimeOut: 2.0
    dishleafnode:
      CommandTimeOutDefault: 140
      AdapterTimeOut: 2.0
      DishAvailabilityCheckTimeout: 30
    mocks:
      enabled: false
      dish: false
      csp: false
      sdp: false

#=== TangoGQL ===#
ska-tango-tangogql:
  enabled: true
  ska-tango-base:
    enabled: false

#=== EDA ===#
ska-tango-archiver:
  enabled: false
  dbname: mid_sw_integration_eda
  dbuser: admin
  port: 5432
  vault:
    secretPath: "kv/data/users/kvsudhirreddy/archiver"
    secretMount: kv
  telescope: SKA-mid
  telescope-environment: MID-STFC

#=== Supporting components ===#
ska-ser-skuid:
  enabled: true

ska-tango-util:
  enabled: true

ska-taranta:
  enabled: true

#=== WMS (Weather Monitoring System) ===#
ska-mid-wms:
  deviceServers:
    wms:
      station_ids: ["s1", "s2"]
      modbus_server_hostnames: ["wms-sim-s1", "wms-sim-s2"]
      modbus_server_ports: ["1502", "1502"]
  labels:
    app: ska-mid-integration
  enabled: true
  ska-tango-base:
    enabled: false
  simulator:
    enabled: false

#=== Pod deletion chart ===#
ska-integration-test-utils:
  enabled: true
