display: ":0"
xauthority: "~/.Xauthority"

enabled: true

legacy_compatibility: true

system: TM-mid
telescope: SKA-mid
subsystem: ska-tmc-mid


labels:
  app: ska-tmc-mid
annotations:
  app.gitlab.com/app: CI_PROJECT_PATH_SLUG
  app.gitlab.com/env: CI_ENVIRONMENT_SLUG

##  Order of instances resolution ##
# .Values.subarray_count
# subarray_count, this will be expanded (1 to N inclusive)
subarray_count: 2

global:
  minikube: false
  tango_host: databaseds-tango-base-test:10000

  ##  Order of instances resolution ##
  # .Values.global.dishes
  # .Values.deviceServers.<device>.instances
  # File, data/<device>.yaml, instances

  # List the dishes, if set, then this list will be applied to instances of:
  # deviceServers.dishmaster, deviceServers.dishleafnode
  dish_devices: ["dishmaster", "dishleafnode"]
  dishes: ["001", "036", "063", "100"]
  

  namespace_dish:
    dish_names: []

  # Instance of the following devices can be expanded (1 to N inclusive) by using subarray_count
  # deviceServers.cspsubarrayleafnode, deviceServers.sdpsubarrayleafnode, deviceServers.subarraynode
  subarray_devices:
    - "cspsubarrayleafnode"
    - "sdpsubarrayleafnode"
    - "subarraynode"


  # fqdn for mid devices
  tmc_subarray_prefix: "ska_mid/tm_subarray_node"
  csp_subarray_ln_prefix: "ska_mid/tm_leaf_node/csp_subarray"
  sdp_subarray_ln_prefix: "ska_mid/tm_leaf_node/sdp_subarray"
  csp_master_ln_prefix: "ska_mid/tm_leaf_node/csp_master"
  sdp_master_ln_prefix: "ska_mid/tm_leaf_node/sdp_master"
  csp_subarray_prefix: "mid-csp/subarray"
  sdp_subarray_prefix: "mid-sdp/subarray"
  dish_suffix: "elt/master"
  csp_master: "mid-csp/control/0"
  sdp_master: "mid-sdp/control/0"
  dish_ln_prefix: "ska_mid/tm_leaf_node/d0"

dsconfig:
  configuration_file: data/tmc-mid-config.json
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-dsconfig
    tag: 1.5.7
    pullPolicy: IfNotPresent

itango:
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-itango
    tag: 9.3.10
    pullPolicy: IfNotPresent

centralnode:
  image:
    registry: artefact.skao.int
    image: ska-tmc-centralnode
    tag: 0.17.5
    pullPolicy: IfNotPresent

subarraynode:
  image:
    registry: artefact.skao.int
    image: ska-tmc-subarraynode
    tag: 0.30.1
    pullPolicy: IfNotPresent

sdpleafnodes:
  image:
    registry: artefact.skao.int
    image: ska-tmc-sdpleafnodes
    tag: 0.20.2
    pullPolicy: IfNotPresent

cspmasterleafnode:
  image:
    registry: artefact.skao.int
    image: ska-tmc-cspleafnodes
    tag: 0.23.5
    pullPolicy: IfNotPresent

cspsubarrayleafnode:
  image:
    registry: artefact.skao.int
    image: ska-tmc-cspleafnodes
    tag: 0.23.5
    pullPolicy: IfNotPresent

dishleafnode:
  image:
    registry: artefact.skao.int
    image: ska-tmc-dishleafnode
    tag: 0.19.7
    pullPolicy: IfNotPresent

resources:
  limits:
    memory: 500Mi
    cpu: 400m
  requests:
    cpu: 200m
    memory: 200Mi


deviceServers:
  centralnode:
    enabled: true
    instances: ["01"]
    subarray_count: 1
    file: "data/centralnode_mid.yaml"
    DishIDs: ["SKA001", "SKA036", "SKA063", "SKA100"]
    RealDishMasterIdentifier: "mid-dish/dish-manager"
    SimulatorDishMasterIdentifier: "elt/master"
    DishVccConfig:
      DishVccUri: "car://gitlab.com/ska-telescope/ska-telmodel-data?ska-sdp-tmlite-repository-1.0.0#tmdata"
      DishVccFilePath: "instrument/ska1_mid_psi/ska-mid-cbf-system-parameters.json"
      Enabled: "true"
      DishKvalueAggregationAllowedPercent: "100.0"
    KValueValidRange:
      min: 1
      max: 1177
    CommandTimeOut: 120
    DishVccInitTimeout: 180
    LivelinessCheckPeriod: 2.0
    EventSubscriptionCheckPeriod: 2.0

  subarraynode:
    enabled: true
    file: "data/subarraynode_mid.yaml"
    DishIDs: ["SKA001", "SKA036", "SKA063", "SKA100"]
    RealDishMasterIdentifier: "mid-dish/dish-manager"
    SimulatorDishMasterIdentifier: "elt/master"
    CspAssignResourcesInterfaceURL: "https://schema.skao.int/ska-csp-assignresources/2.0"
    CspScanInterfaceURL: "https://schema.skao.int/ska-csp-scan/2.0"
    SdpScanInterfaceURL: "https://schema.skao.int/ska-sdp-scan/0.4"
    CommandTimeOut: 110
    AbortCommandTimeOut: 130
    LivelinessCheckPeriod: 1.5
    EventSubscriptionCheckPeriod: 1.5

  sdpsubarrayleafnode:
    enabled: true
    file: "data/sdpsubarrayleafnode.yaml"
    CommandTimeOut: 50
    AdapterTimeOut: 2
    LivelinessCheckPeriod: 1.5
    EventSubscriptionCheckPeriod: 1.5
    SDPSubarrayAdminModeEnabled: false

  sdpmasterleafnode:
    enabled: true
    instances: ["01"]
    file: "data/sdpmasterleafnode.yaml"
    AdapterTimeOut: 2
    LivelinessCheckPeriod: 1.5
    EventSubscriptionCheckPeriod: 1.5
    SDPMasterAdminModeEnabled: false

  cspmasterleafnode:
    enabled: true
    instances: ["01"]
    file: "data/cspmasterleafnode.yaml"
    AdapterTimeOut: 2.0
    LivelinessCheckPeriod: 1.5
    EventSubscriptionCheckPeriod: 1.5


  cspsubarrayleafnode:
    enabled: true
    file: "data/cspsubarrayleafnode.yaml"
    TelmodelSource: gitlab://gitlab.com/ska-telescope/ska-telmodel-data?main#tmdata
    TelmodelPath: instrument/ska1_mid/layout/mid-layout.json
    DelayCadence: 10.0
    DelayValidityPeriod: 20.0
    DelayModelTimeInAdvance: 30
    CommandTimeOut: 50
    AdapterTimeOut: 2.0
    LivelinessCheckPeriod: 1.5
    EventSubscriptionCheckPeriod: 1.5

  dishleafnode:
    enabled: true
    file: "data/dishleafnode.yaml"
    IsDishAbortCommandsEnabled: "True"
    resources:
      limits:
        memory: 1000Mi
        cpu: 2500m
      requests:
        cpu: 2000m
        memory: 300Mi
    CommandTimeOut: 90
    MaxTrackTableRetry: 3
    TrackTableRetryDuration: 0.2
    LivelinessCheckPeriod: 1.5
    EventSubscriptionCheckPeriod: 1.5
    AdapterTimeOut: 2.0
    DishAvailabilityCheckTimeout: 30

  dishpointingdevice:
    enabled: true
    file: "data/dishpointingdevice.yaml"
    TrackTableUpdateRate: 50
    TrackTableInAdvance: 7
    ElevationMaxLimit: 90.0
    ElevationMinLimit: 15.0
    AzimuthMaxLimit: 270
    AzimuthMinLimit: -270

  mocks:
    enabled: false
    file: "data/mocks.yaml"
    dish: false
    csp: false
    sdp: false

nodeSelector: {}

affinity: {}

tolerations: []

# not needed, already available in CI/CD
# ingress:
#   enabled: true
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
#   host: ""  # You can put your domain here or leave it blank for IP-based access
#   path: /
#   serviceName: ska-k8s-config-exporter-service
#   servicePort: 8080
