display: ":0"
xauthority: "~/.Xauthority"

enabled: true

legacy_compatibility: true

system: TM-mid
telescope: SKA-mid
subsystem: ska-tmc-mid

labels:
  app: ska-tmc-mid
annotations:
  app.gitlab.com/app: CI_PROJECT_PATH_SLUG
  app.gitlab.com/env: CI_ENVIRONMENT_SLUG

##  Order of instances resolution ##
# .Values.subarray_count
# subarray_count, this will be expanded (1 to N inclusive)
subarray_count: 2

global:
  minikube: false
  tango_host: databaseds-tango-base-test:10000
  dishids: &dish_ids ["SKA001", "SKA036", "SKA063", "SKA100"]

  # List the dishes, if set, then this list will be applied to instances of:
  # deviceServers.dishmaster, deviceServers.dishleafnode
  dish_devices: ["dishmaster", "dishleafnode"]
  dishes: ["001", "036", "063", "100"]

  domain: "mid-tmc"

  namespace_dish:
    dish_names: []

  # Instance of the following devices can be expanded (1 to N inclusive) by using subarray_count
  # deviceServers.cspsubarrayleafnode, deviceServers.sdpsubarrayleafnode, deviceServers.subarraynode
  subarray_devices:
    - "cspsubarrayleafnode"
    - "sdpsubarrayleafnode"
    - "subarraynode"

  # fqdn for mid devices
  tmc_central_node: "mid-tmc/central-node/0"
  tmc_subarray_prefix: "mid-tmc/subarray"
  csp_subarray_ln_prefix: "mid-tmc/subarray-leaf-node-csp/"
  sdp_subarray_ln_prefix: "mid-tmc/subarray-leaf-node-sdp/"
  csp_master_ln: "mid-tmc/leaf-node-csp/0"
  sdp_master_ln: "mid-tmc/leaf-node-sdp/0"
  csp_subarray_prefix: "mid-csp/subarray"
  sdp_subarray_prefix: "mid-sdp/subarray"
  dish_suffix: "mid-dish/dish-manager"
  dish_manager_suffix: "mid-dish/dish-manager/ska"
  csp_master: "mid-csp/control/0"
  sdp_master: "mid-sdp/control/0"
  dish_ln_prefix: "mid-tmc/leaf-node-dish/ska"
  dishln_pointing_suffix: "mid-tmc/dish-pointing/ska"
  mid_sdp_subarray_1: "mid-sdp/subarray/01"
  mid_sdp_subarray_2: "mid-sdp/subarray/02"
  mid_sdp_queueconnector: "mid-sdp/queueconnector/01"
  mid_csp_control: "mid-csp/control/0"
  mid_csp_subarray_1: "mid-csp/subarray/01"
  mid_csp_subarray_2: "mid-csp/subarray/02"
  resource_monitor_prefix: "mid-tmc/resource-monitor/"

dsconfig:
  configuration_file: data/tmc-mid-config.json
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-dsconfig
    tag: 1.5.7
    pullPolicy: IfNotPresent

itango:
  image:
    registry: artefact.skao.int
    image: ska-cicd-k8s-tools-build-deploy
    tag: 0.13.4
    pullPolicy: IfNotPresent

centralnode:
  image:
    registry: registry.gitlab.com/ska-telescope/ska-tmc/ska-tmc-centralnode
    image: ska-tmc-centralnode
    tag: 0.29.2-dev.c13981d02
    pullPolicy: IfNotPresent

subarraynode:
  image:
    registry: artefact.skao.int
    image: ska-tmc-subarraynode
    tag: 0.49.1
    pullPolicy: IfNotPresent

sdpleafnodes:
  image:
    registry: artefact.skao.int
    image: ska-tmc-sdpleafnodes
    tag: 0.25.0
    pullPolicy: IfNotPresent

cspmasterleafnode:
  image:
    registry: artefact.skao.int
    image: ska-tmc-cspleafnodes
    tag: 0.38.0
    pullPolicy: IfNotPresent

cspsubarrayleafnode:
  image:
    registry: artefact.skao.int
    image: ska-tmc-cspleafnodes
    tag: 0.38.0
    pullPolicy: IfNotPresent

dishleafnode:
  image:
    registry: artefact.skao.int
    image: ska-tmc-dishleafnode
    tag: 0.30.0
    pullPolicy: IfNotPresent

skatmcsimulators:
  image:
    registry: artefact.skao.int
    image: ska-tmc-simulators
    tag: 1.9.5
    pullPolicy: IfNotPresent

resource_monitor:
  image:
    registry: artefact.skao.int
    image: ska-tmc-resource-monitor
    tag: 0.5.0
    pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 200m
    memory:

deviceServers:
  centralnode:
    enabled: true
    instances: ["01"]
    subarray_count: 1
    file: "data/centralnode_mid.yaml"
    DishIDs: *dish_ids
    DishVccConfig:
      DishVccUri: "car://gitlab.com/ska-telescope/ska-telmodel-data?ska-sdp-tmlite-repository-1.0.0#tmdata"
      DishVccFilePath: "instrument/ska1_mid_psi/ska-mid-cbf-system-parameters.json"
      Enabled: "true"
      DishKvalueAggregationAllowedPercent: "100.0"
    KValueValidRange:
      min: 1
      max: 1177
    CommandTimeOutDefault: 120
    DishVccInitTimeout: 180
    LivelinessCheckPeriod: 2.0
    EventSubscriptionCheckPeriod: 2.0
    DefaultArrayLayoutSourceURIs: "gitlab://gitlab.com/ska-telescope/ska-telmodel-data?main#tmdata"
    DefaultArrayLayoutPath: "instrument/ska1_mid/layout/mid-layout.json"
    family: "central-node"
    member: "0"
    global_pointing_model:
      version: "1.0.0"
      interface: "https://schema.skao.int/ska-mid-dish-gpm/1.2"
      data_sources_prefix: "gitlab://gitlab.com/ska-telescope/ska-tmc/ska-tmc-simulators"
      file_path_prefix: "instrument/ska_mid1/global_pointing_model_data"

  subarraynode:
    enabled: true
    file: "data/subarraynode_mid.yaml"
    DishIDs: *dish_ids
    CspAssignResourcesInterfaceURL: "https://schema.skao.int/ska-csp-assignresources/2.0"
    CspScanInterfaceURL: "https://schema.skao.int/ska-csp-scan/2.2"
    SdpScanInterfaceURL: "https://schema.skao.int/ska-sdp-scan/1.1"
    CommandTimeOutDefault: 110
    AbortCommandTimeOut: 130
    LivelinessCheckPeriod: 1.5
    EventSubscriptionCheckPeriod: 1.5
    family: "subarray"
    resources:
      limits:
        cpu: 600m
        memory: 1000Mi
      requests:
        cpu: 400m
        memory: 300Mi

  sdpsubarrayleafnode:
    enabled: true
    file: "data/sdpsubarrayleafnode.yaml"
    CommandTimeOutDefault: 50
    AdapterTimeOut: 2
    LivelinessCheckPeriod: 1.5
    EventSubscriptionCheckPeriod: 1.5
    SDPSubarrayAdminModeEnabled: true
    family: "subarray-leaf-node-sdp"

  sdpmasterleafnode:
    enabled: true
    instances: ["01"]
    file: "data/sdpmasterleafnode.yaml"
    AdapterTimeOut: 2
    LivelinessCheckPeriod: 1.5
    EventSubscriptionCheckPeriod: 1.5
    SDPMasterAdminModeEnabled: true
    family: "leaf-node-sdp"
    member: "0"

  cspmasterleafnode:
    enabled: true
    instances: ["01"]
    file: "data/cspmasterleafnode.yaml"
    AdapterTimeOut: 2.0
    LivelinessCheckPeriod: 1.5
    EventSubscriptionCheckPeriod: 1.5
    CommandTimeOutDefault: 30
    family: "leaf-node-csp"
    member: "0"

  cspsubarrayleafnode:
    enabled: true
    file: "data/cspsubarrayleafnode.yaml"
    TelmodelSource: gitlab://gitlab.com/ska-telescope/ska-telmodel-data?main#tmdata
    TelmodelPath: instrument/ska1_mid/layout/mid-layout.json
    DelayCadence: 10.0
    DelayValidityPeriod: 20.0
    DelayModelTimeInAdvance: 30
    CommandTimeOutDefault: 50
    AdapterTimeOut: 2.0
    LivelinessCheckPeriod: 1.5
    EventSubscriptionCheckPeriod: 1.5
    family: "subarray-leaf-node-csp"

  dishleafnode:
    enabled: true
    file: "data/dishleafnode.yaml"
    IsDishAbortEnabled: True
    resources:
      limits:
        memory: 3000Mi
      requests:
        cpu: 2000m
        memory: 700Mi
    CommandTimeOutDefault: 90
    MaxTrackTableRetry: 3
    TrackTableRetryDuration: 0.2
    LivelinessCheckPeriod: 1.5
    EventSubscriptionCheckPeriod: 1.5
    AdapterTimeOut: 2.0
    DishAvailabilityCheckTimeout: 30
    family: "leaf-node-dish"
    prefix_member: "SKA"
    weather_station_device_names: 
      - ""
    max_allowed_wind_speed: 13.5
    max_allowed_ops_wind_speed: 10
    max_allowed_gust_wind_speed: 20  
    max_allowed_wind_speed_difference: 4.5
    wind_speed_measurement_time_window: 1000
    gust_wind_speed_measurement_time_window: 3
    mean_wind_speed_measurement_time_window: 600
    max_allowed_ops_mean_wind_speed_measurement_time_window: 600
    max_temp_threshold: 40.0
    min_temp_threshold: -5
    time_delta: 1000.0
    temp_delta: 10.0 #inflated 
    enable_auto_stow: false

  dishpointingdevice:
    enabled: true
    file: "data/dishpointingdevice.yaml"
    TrackTableUpdateRate: 50
    TrackTableInAdvance: 7
    ElevationMaxLimit: 90.0
    ElevationMinLimit: 15.0
    AzimuthMaxLimit: 270
    AzimuthMinLimit: -270
    resources:
      limits:
        memory: 1000Mi
        cpu: 500m
      requests:
        cpu: 500m
        memory: 500Mi

  resourcemonitor:
    enabled: true
    instances: ["01"]
    file: "data/resourcemonitor.yaml"
    LivelinessCheckPeriod: 1.0
    EventSubscriptionCheckPeriod: 1.0
    family: "resource-monitor"
    DishLeafNodePrefix: "mid-tmc/leaf-node-dish/"
    SubarrayPrefix: "mid-tmc/subarray/"
    DishType: "SKA"
    DishIDs: *dish_ids
    MidSubarrayNodeFQDNs: ["mid-tmc/subarray/01", "mid-tmc/subarray/02"]

  mocks:
    enabled: false
    file: "data/mocks.yaml"
    dish: false
    csp: false
    sdp: false

ska-mid-wms:
  legacy_compatibility: true
  dev-name: "mid/wms/0"
  ska-tango-base:
    enabled: false
    itango:
      enabled: false

nodeSelector: {}

affinity: {}

tolerations: []
