display: ":0"
xauthority: "~/.Xauthority"

legacy_compatibility: true

global:
  retry: 
  - "--sleep=1"
  - "--tries=100"
  sub-system:
    ska-tango-util:
      enabled: false
    ska-tango-base:
      enabled: false
    ska-tango-taranta:
      enabled: false
  tango_host: databaseds-tango-base-test:10000
  dsconfig:
    timeout: 300s
    image:
      registry: artefact.skao.int
      image: ska-tango-images-tango-dsconfig
      tag: 1.5.7
      pullPolicy: IfNotPresent
  itango:
    image:
      registry: artefact.skao.int
      image: ska-cicd-k8s-tools-build-deploy
      tag: 0.13.4
      pullPolicy: IfNotPresent
  sdp:
    processingNamespace: ska-tmc-integration-sdp

ska-tango-base:
  enabled: true
  vnc:
    replicas: 1
    enabled: false
  tangorest:
    enabled: false
    replicas: 1
  tangodb:
    use_pv: false

ska-taranta:
  enabled: false

# Tmc-Mid
tmc-mid:
  labels:
    app: ska-tmc-integration
  enabled: true

  deviceServers:
    mocks:
      enabled: true
      dish: true
      csp: true
      sdp: true

ska-sdp:
  resources:
    limits:
      memory: 200Mi
      cpu: 0.1
    requests:
      memory: 100Mi
      cpu: 0.2
  enabled: false
  lmc:
    resources:
      limits:
        memory: 500Mi
        cpu: 0.5
      requests:
        memory: 100Mi
        cpu: 0.3
    prefix: mid
    nsubarray: 1
  data-pvc:
    create:
      enabled: true
      size: 100Mi
      storageClassName: nfss1
  ska-tango-base:
    enabled: false

# SKUID
ska-ser-skuid:
  labels:
    app: ska-tmc-integration
  enabled: true
  skuid:
    use_pv: false
    config:
      generator_id: mvp01
  
ska-tango-alarmhandler:
  labels: 
    app: ska-tmc-integration
  enabled: true
  legacy_compatibility: true


ska-csp-lmc-mid:
  labels: 
    app: ska-tmc-integration
  enabled: false

ska-mid-cbf-mcs:
  labels: 
    app: ska-tmc-integration

ska-mid-cbf-tmleafnode:
  labels: 
    app: ska-tmc-integration

ska-tango-tangogql-ariadne:
  enabled: true
  ska-tango-base:
    enabled: false

ska-tango-tangogql:
  ska-tango-base:
    enabled: false

simulator:
  enabled: true
  name: wms-sim
  containers:
    registry: registry.gitlab.com
    image: ska-telescope/ska-mid-wms-interface/ska-mid-wms-interface
    tag: 966329b7
    pullPolicy: IfNotPresent

mid_wms:
  deviceServers:
    wms:
      station_ids: ["s1", "s2"]
      modbus_server_hostnames: ["wms-sim-s1", "wms-sim-s2"]
      modbus_server_ports: ["1502", "1502"]
  labels:
    app: ska-tmc-integration
  enabled: true
  ska-tango-base:
    enabled: false
  simulator:
    enabled: false

