tmc-mid:
  enabled: true
  deviceServers:
    mocks:
      enabled: true
      sdp: false
      csp: true
      dish: true

ska-tango-base:
  enabled: true 

ska-sdp:
  labels:
    app: ska-mid-integration
  legacy_compatibility: true
  enabled: true
  lmc:
    loadBalancer: true
    prefix: mid
    nsubarray: 1
  console:
    enabled: true
  ska-sdp-qa:
    kafka:
      resources:
        limits:
          memory: 100Mi
        requests:
          cpu: 100m
          memory: 50Mi
      livenessProbe:
        initialDelaySeconds: 30
        failureThreshold: 5
      zookeeper:
        resources:
          requests:
            cpu: 100m
  ska-tango-base:
    enabled: false



ska-dish-lmc:
  enabled: false

ska-csp-lmc-mid:
  enabled : false

ska-taranta:
  enabled : false 
  
  
ska-ser-skuid:
  enabled : false


ska-mid-cbf-mcs:
  enabled : false

ska-mid-cbf-tmleafnode:
  enabled : false
